//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainingapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dept
    {
        public Dept()
        {
            this.Employee1 = new HashSet<Employee1>();
        }
    
        public int DeptId { get; set; }
        public string Dname { get; set; }
    
        public virtual ICollection<Employee1> Employee1 { get; set; }
    }
}
