//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainingapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee1
    {
        public Employee1()
        {
            this.EmpRoles = new HashSet<EmpRole>();
        }
    
        public int EmpID { get; set; }
        public string Empname { get; set; }
        public int Age { get; set; }
        public int Contact { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int DeptID { get; set; }
        public string Address { get; set; }
    
        public virtual Dept Dept { get; set; }
        public virtual ICollection<EmpRole> EmpRoles { get; set; }
    }
}
