//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainingapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpRole
    {
        public int EmpId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Employee1 Employee1 { get; set; }
        public virtual EmpRole EmpRole1 { get; set; }
        public virtual EmpRole EmpRole2 { get; set; }
    }
}
